/*
 * Enemy.cs
 * 
 * This script controls the enemy behavior in the game.
 * 
 * Not generated by AI.
 */

using UnityEngine;
using System.Collections;
using System.Collections.Generic;


public class Enemy : MonoBehaviour
{
    [SerializeField]
    private float _speed = 4.0f;

    //[SerializeField]
    private Player _player;
    private Animator _anim;

    private AudioSource _audioSource;
    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        
        _player = GameObject.Find("Player").GetComponent<Player>();
        _audioSource = GetComponent<AudioSource>();

        if (_player == null)
        {
            Debug.LogError("The Player is NULL.");
        }

        _anim = GetComponent<Animator>();

        if (_anim == null)
        {
            Debug.LogError("Animator is NULL");
        }

    }
    // Update is called once per frame
    void Update()
    {
        transform.Translate(Vector3.down * _speed * Time.deltaTime);
        if (transform.position.y < -6.0f)
        {
            float randomX = Random.Range(-9.0f, 9.0f);
            transform.position = new Vector3(randomX, 7.0f, 0);
        }

    }

    private void OnTriggerEnter2D(Collider2D other)
    {
        if (other.tag == "Player")
        {
            // Damage the player
            Player player = other.transform.GetComponent<Player>();
            if (player != null)
            {
                player.Damage();
            }

            _anim.SetTrigger("OnEnemyDeath");
            _speed = 0;

            // Destroy enemy
            _audioSource.Play();

            Destroy(this.gameObject, 2.8f);
        }
        else if (other.tag == "Laser")
        {
            // Destroy laser
            Destroy(other.gameObject);
            if (_player != null)
            {
                _player.AddScore(10);
            }   

            _anim.SetTrigger("OnEnemyDeath");
            _speed = 0;
            // Destroy enemy
            _audioSource.Play();

            Destroy(this.gameObject, 2.8f);
        }
    }
}
