/*
 * Laser.cs 
 *  
 * this script controls the laser behavior in the game.
 *
 *  not generated by AI.
 */

using UnityEngine;
using System.Collections.Generic;
using System.Collections;

public class Laser : MonoBehaviour
{
    [SerializeField]
    private float _speed = 8.0f;

    void Update()
    {
        transform.Translate(Vector3.up * _speed * Time.deltaTime);

        if (transform.position.y > 7.0f)
        {

            if (transform.parent != null)
            {
                Destroy(transform.parent.gameObject);
            }

            Destroy(this.gameObject);
        }

    }
}
